version: "3.9"

services:
    ng-asp-forum:
        image: ng-asp-forum
        restart: always

        build:
            context: .
            dockerfile: Dockerfile

        depends_on:
            - mysql
        
        environment:
            - EMAIL_USERNAME
            - EMAIL_PASSWORD
            - EMAIL_SERVER
            - AUTH_ISSUER
            - AUTH_AUDIENCE
            - AUTH_SECRET
            - ConnectionStrings__DefaultConnection

        ports:
            - 5000:5000
            - 8080:8080

        network_mode: "host"

    mysql:
        image: mysql:8.1

        command: --sql_mode=""

        volumes:
            - mysql:/var/lib/mysql

        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE

        ports:
            - 3306:3306

volumes:
    mysql: