version: "3.9"

volumes:
    db:

services:
    ng-asp-forum:
        image: ng-asp-forum
        restart: always

        build:
            context: .
            dockerfile: Dockerfile
        
        volumes:
            - db:/root/.local/share

        environment:
            - EMAIL_USERNAME
            - EMAIL_PASSWORD
            - EMAIL_SERVER
            - AUTH_ISSUER
            - AUTH_AUDIENCE
            - AUTH_SECRET

        ports:
            - 5000:5000
            - 8080:8080

        network_mode: "host"